// Content coverage report: every curriculum item, its topic, question count and
// verification status. Writes CONTENT_COVERAGE.md next to the track.
import fs from "node:fs";
import { examBlueprint } from "../lib/engine/exam";
import path from "node:path";
import { getAllTracks, CONTENT_ROOT } from "../lib/content/load";

const TARGET = { default: [8, 12], promql: [10, 14] } as const;

for (const track of getAllTracks()) {
  const lines: string[] = [];
  lines.push(`# Content coverage: ${track.title}`, "");
  lines.push(`Generated by \`npm run content:coverage\`.`, "");
  if (track.curriculumSource) lines.push(`Curriculum: [${track.curriculumSource.title}](${track.curriculumSource.url})`, "");

  const all = track.topics.flatMap((t) => t.questions);
  const st = (xs: { status: string }[], s: string) => xs.filter((x) => x.status === s).length;
  const withContent = track.topics.filter((t) => t.lesson && t.questions.length).length;
  lines.push(`**${withContent}/${track.topics.length} curriculum items have a lesson and questions · ${all.length} questions** (${st(all, "draft")} draft, ${st(all, "source-checked")} source-checked, ${st(all, "human-verified")} human-verified)`, "");

  for (const d of track.domains) {
    const topics = track.topics.filter((t) => t.domain === d.id);
    const [min, max] = d.id === "promql" ? TARGET.promql : TARGET.default;
    lines.push(`## ${d.title} (${d.weight}%)`, "");
    lines.push("| # | Curriculum item | Topic | Lesson | Questions | Target | Status (draft / source-checked / human-verified) |");
    lines.push("|---|---|---|---|---|---|---|");
    for (const t of topics) {
      const n = t.questions.length;
      const flag = n === 0 ? "❌" : n < min ? "⚠️" : "✅";
      const lesson = t.lesson ? `${t.lesson.status}` : "—";
      lines.push(`| ${t.index + 1} | ${t.curriculumItem} | \`${t.id}\` | ${lesson} | ${flag} ${n} | ${min}–${max} | ${st(t.questions, "draft")} / ${st(t.questions, "source-checked")} / ${st(t.questions, "human-verified")} |`);
    }
    lines.push("");
  }

  if (track.examPool.length) {
    const per = track.exam ? examBlueprint(track.domains, track.exam.questions) : {};
    lines.push("## Exam-only question bank", "");
    lines.push(`Used only by the pre-course check and mock exams, never in daily practice. **${track.examPool.length} questions** (${st(track.examPool, "draft")} draft, ${st(track.examPool, "source-checked")} source-checked, ${st(track.examPool, "human-verified")} human-verified).`, "");
    lines.push("| Domain | Questions | Per full mock | Distinct mocks |");
    lines.push("|---|---|---|---|");
    for (const d of track.domains) {
      const n = track.examPool.filter((q) => q.domain === d.id).length;
      const need = per[d.id] ?? 0;
      lines.push(`| ${d.title} | ${n} | ${need} | ${need ? Math.floor(n / need) : "—"} |`);
    }
    lines.push("");
  }
  const out = path.join(CONTENT_ROOT, track.id, "CONTENT_COVERAGE.md");
  fs.writeFileSync(out, lines.join("\n"));
  console.log(`Wrote ${path.relative(process.cwd(), out)}`);
}
