/**
 * Queries the playground engine is checked against real Prometheus with
 * (see scripts/playground-golden.ts and tests/playground-golden.test.ts).
 * Times are offsets in minutes from the end of the dataset.
 */
export const INSTANT_TIMES_MIN = [0, -7.5, -43, -79, -80.25, -170];

export const INSTANT_QUERIES: string[] = [
  // Selectors, matchers, lookback, offset, @
  "up",
  "up == 0",
  'http_requests_total{status=~"5.."}',
  'http_requests_total{status!~"2..", path!="/healthz"}',
  'http_requests_total{method="POST", status="200"}',
  '{__name__=~"node_load1|queue_depth"}',
  '{job="batch"}',
  'up{job=~"api|db"}',
  "http_requests_total offset 1h",
  'up{instance="api-3:8080"} offset 80m',
  "node_load1 @ 1790852400",
  "rate(http_requests_total[5m] @ 1790853000)",
  "node_load1 offset -5m",
  "app_build_info",
  // rate / irate / increase / delta / deriv / predict
  "rate(http_requests_total[5m])",
  "rate(http_requests_total[1m])",
  "rate(http_requests_total[30s])",
  "rate(http_requests_total[1h])",
  "irate(http_requests_total[5m])",
  "increase(http_requests_total[1h])",
  'increase(http_requests_total{instance="api-3:8080"}[10m])',
  "rate(process_cpu_seconds_total[5m])",
  "rate(node_cpu_seconds_total[5m])",
  "delta(queue_depth[10m])",
  "idelta(queue_depth[5m])",
  "deriv(node_filesystem_avail_bytes[30m])",
  "deriv(process_resident_memory_bytes[1h])",
  "predict_linear(node_filesystem_avail_bytes[1h], 4 * 3600)",
  "predict_linear(node_filesystem_avail_bytes[1h], 4 * 3600) < 0",
  "resets(http_requests_total[2h])",
  "resets(process_cpu_seconds_total[3h])",
  "changes(app_build_info[3h])",
  "changes(process_start_time_seconds[3h])",
  "changes(queue_depth[10m])",
  // _over_time
  "avg_over_time(node_load1[1h])",
  "min_over_time(queue_depth[30m])",
  "max_over_time(queue_depth[30m])",
  "sum_over_time(up[10m])",
  "count_over_time(up[1h])",
  "last_over_time(node_load1[10m])",
  "present_over_time(app_build_info[1h])",
  "stddev_over_time(node_load1[1h])",
  "stdvar_over_time(queue_depth[1h])",
  "quantile_over_time(0.9, queue_depth[1h])",
  "quantile_over_time(0.5, node_load1[30m])",
  "absent_over_time(app_build_info{version=\"1.4.2\", instance=\"api-3:8080\"}[30m])",
  'absent_over_time(nonexistent_metric{job="x"}[5m])',
  // Subqueries
  "max_over_time(rate(http_requests_total[5m])[1h:1m])",
  "max_over_time(rate(http_requests_total[5m])[1h:])",
  "avg_over_time(sum by (instance) (rate(http_requests_total[5m]))[30m:30s])",
  'min_over_time(sum(rate(http_requests_total{status="500"}[5m]))[2h:5m])',
  "rate(http_requests_total[5m])[10m:1m] offset 5m",
  "deriv(sum(node_filesystem_avail_bytes)[30m:1m])",
  "max_over_time(up[30m:15s])",
  // Aggregations
  "sum(rate(http_requests_total[5m]))",
  "sum by (job) (rate(http_requests_total[5m]))",
  "sum by (instance, status) (rate(http_requests_total[5m]))",
  "sum without (instance) (rate(http_requests_total[5m]))",
  "sum without (method, path, status) (rate(http_requests_total[5m]))",
  "avg by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
  "max by (job) (scrape_duration_seconds)",
  "min(node_memory_MemAvailable_bytes)",
  "count(up)",
  "count by (job) (up)",
  "count(up == 1)",
  "group by (job) (up)",
  "stddev(rate(http_requests_total{path=\"/api/orders\",method=\"GET\",status=\"200\"}[5m]))",
  "stdvar by (job) (scrape_duration_seconds)",
  "topk(3, rate(http_requests_total[5m]))",
  "topk(1, sum by (instance) (rate(http_requests_total[5m])))",
  "bottomk(2, node_memory_MemAvailable_bytes)",
  "topk by (path) (1, rate(http_requests_total[5m]))",
  "quantile(0.5, rate(http_requests_total[5m]))",
  "quantile by (job) (0.9, scrape_duration_seconds)",
  "count_values(\"version\", app_build_info)",
  "count_values(\"count\", count by (job) (up))",
  "count_values without (instance) (\"v\", up)",
  "sum(up) by (job)",
  "avg(node_load1)",
  "sum(nonexistent_metric)",
  "count(nonexistent_metric)",
  // Binary operators
  "node_load1 > 1",
  "node_load1 > bool 1",
  "1 < node_load1",
  "2 > bool node_load1",
  "up + 1",
  "2 * up",
  "up - up",
  "-node_load1",
  "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes",
  "1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes",
  "100 * (1 - node_filesystem_avail_bytes / node_filesystem_size_bytes)",
  "sum by (job) (rate(http_requests_total{status=~\"5..\"}[5m])) / sum by (job) (rate(http_requests_total[5m]))",
  "sum by (instance) (rate(http_requests_total{status=\"500\"}[5m])) / sum by (instance) (rate(http_requests_total[5m])) > 0.05",
  "rate(http_requests_total[5m]) / on(instance) group_left sum by (instance) (rate(http_requests_total[5m]))",
  "rate(http_requests_total[5m]) * on(instance) group_left(version) app_build_info",
  "app_build_info * on(instance) group_right(version) rate(http_requests_total[5m])",
  "sum by (instance) (rate(http_requests_total[5m])) / ignoring(job) sum by (instance, job) (rate(http_requests_total[5m]))",
  "node_memory_MemAvailable_bytes / on(instance) node_memory_MemTotal_bytes",
  "node_memory_MemAvailable_bytes / ignoring(job) node_memory_MemTotal_bytes",
  "up and on(instance) rate(process_cpu_seconds_total[5m]) > 0.05",
  "up{job=\"api\"} unless on(instance) app_build_info{version=\"1.5.0\"}",
  "up{job=\"node\"} or up{job=\"db\"}",
  "sum(rate(http_requests_total{status=\"503\"}[5m])) or vector(0)",
  "rate(http_requests_total[5m]) > 1 and rate(http_requests_total[5m]) < 5",
  "up == on(job, instance) up",
  "node_load1 > on(instance) node_load1 offset 1h",
  "2 ^ 3 ^ 2",
  "10 % 3",
  "-7 % 3",
  "1 + 2 * 3 - 4 / 2",
  "5 > bool 3",
  "node_load1 % 0.5",
  "node_load1 ^ 2",
  "atan2(1, 2) + 0",
  "node_load1 atan2 node_load1",
  // Functions
  "abs(-node_load1)",
  "ceil(node_load1)",
  "floor(node_load1)",
  "round(node_load1)",
  "round(node_load1, 0.1)",
  "sqrt(node_load1)",
  "exp(node_load1)",
  "ln(node_load1)",
  "log2(node_memory_MemTotal_bytes)",
  "log10(node_memory_MemTotal_bytes)",
  "sgn(delta(queue_depth[5m]))",
  "clamp(queue_depth, 5, 40)",
  "clamp_min(node_load1, 1)",
  "clamp_max(node_load1, 1)",
  "clamp(queue_depth, 10, 5)",
  "time()",
  "time() - process_start_time_seconds",
  "time() - batch_job_last_success_timestamp_seconds > 86400",
  "timestamp(up)",
  "time() - timestamp(up)",
  "timestamp(sum(up))",
  "vector(1)",
  "vector(time())",
  "scalar(sum(up))",
  "scalar(up)",
  "sum(up) - scalar(count(up))",
  "sort(node_load1)",
  "sort_desc(rate(http_requests_total[5m]))",
  "label_replace(up, \"host\", \"$1\", \"instance\", \"(.*):.*\")",
  "label_replace(up, \"port\", \"${1}\", \"instance\", \".*:(.*)\")",
  "label_replace(up, \"instance\", \"\", \"instance\", \".*\")",
  "label_replace(up, \"x\", \"$1\", \"nonexistent\", \"(.*)\")",
  "label_join(up, \"target\", \"/\", \"job\", \"instance\")",
  "label_join(up, \"joined\", \",\")",
  "absent(up{job=\"api\"})",
  "absent(nonexistent_metric{job=\"x\", env=~\"prod\"})",
  "absent(up{job=\"missing\"})",
  "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
  "histogram_quantile(0.5, sum by (le, path) (rate(http_request_duration_seconds_bucket[5m])))",
  "histogram_quantile(0.99, sum by (le, instance) (rate(http_request_duration_seconds_bucket[10m])))",
  "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket[5m]))",
  "histogram_quantile(1, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
  "histogram_quantile(0, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
  "histogram_quantile(1.5, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
  "sum(rate(http_request_duration_seconds_bucket{le=\"0.25\"}[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
  "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
  "db_query_duration_seconds{quantile=\"0.99\"}",
  "rate(db_query_duration_seconds_sum[5m]) / rate(db_query_duration_seconds_count[5m])",
  "day_of_week()",
  "hour()",
  "minute(process_start_time_seconds)",
  "month(batch_job_last_success_timestamp_seconds)",
  "year()",
  "day_of_month()",
  "day_of_year()",
  "days_in_month()",
  "pi()",
];

/** Range queries: [query, startMin, endMin, stepSeconds]. */
export const RANGE_QUERIES: [string, number, number, number][] = [
  ["sum by (instance) (rate(http_requests_total[5m]))", -60, 0, 60],
  ["up", -90, -70, 15],
  ["rate(http_requests_total{instance=\"api-3:8080\"}[1m])", -90, -70, 30],
  ["histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))", -60, 0, 120],
  ["max_over_time(rate(http_requests_total{status=\"500\"}[5m])[10m:1m])", -60, -20, 60],
  ["time()", -10, 0, 60],
  ["queue_depth", -30, 0, 45],
  ["predict_linear(node_filesystem_avail_bytes[30m], 3600)", -120, 0, 600],
  ["node_load1 @ end()", -30, 0, 300],
  ["sum(rate(http_requests_total[5m])) @ start()", -30, 0, 300],
  ["count(up == 1)", -85, -75, 15],
];
